# MIMIC-Multimodal: Master Dataset Generation

The data structure of master dataset is inspired by 
Soenksen, L. R. et al. Integrated multimodal artificial intelligence framework for healthcare applications. npj Digit. Med. 5, 149 (2022).

For more details, please visit:
https://physionet.org/content/haim-multimodal/1.0.1/

For data access and description, please visit:
https://mimic.mit.edu/

MIMIC-IV https://physionet.org/content/mimiciv/2.2/#files-panel \
MIMIC-CXR https://physionet.org/content/mimic-cxr/2.0.0/#files-panel \
MIMIC-CXR-JPG https://physionet.org/content/mimic-cxr-jpg/2.0.0/ \
MIMIC-IV-Note https://physionet.org/content/mimic-iv-note/2.2/note/#files-panel

In [1]:
import numpy as np
import pandas as pd
import pickle
import datetime as dt
from pandasql import sqldf
from data_utils import *

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

In [2]:
# File path

# # MIMIC-IV
# mimiciv_hosp_path = '../mimic-iv-2.2/hosp/'
# mimiciv_icu_path = '../mimic-iv-2.2/icu/'
# # MIMIV-CXR & MIMIC-CXR-JPG
# mimiciv_cxr_path = '../mimic-cxr/'
# mimiciv_cxr_jpg_path = '../mimic-cxr-jpg/'
# # MIMIC-IV-Note
# mimiciv_note_path = '../mimic-iv-note/note/'

# MIMIC-IV
mimiciv_hosp_path = Path('~/MIMICWorkspace/MIMIC-IV-Parquet/physionet.org/files/mimiciv/3.1/hosp/').expanduser()
mimiciv_icu_path = Path('~/MIMICWorkspace/MIMIC-IV-Parquet/physionet.org/files/mimiciv/3.1/icu/').expanduser()
# MIMIV-CXR & MIMIC-CXR-JPG
mimiciv_cxr_path = Path('~/MIMICWorkspace/MIMIC-CXR/2.1.0/').expanduser()
mimiciv_cxr_jpg_path = Path('~/MIMICWorkspace/mimic-cxr-jpg/2.1.0/').expanduser() 
# MIMIC-IV-Note
mimiciv_note_path = Path('~/MIMICWorkspace/MIMIC-IV-Note-Parquet/mimic-iv-note-deidentified-free-text-clinical-notes-2.2/note/').expanduser()

## Load Data
For memory efficiency, we first load all files into  **Dask DataFrames** \
When processing is required, we call **ddf.compute()** to convert the data into a Pandas DataFrame

### read files by folder

In [3]:
# MIMIC-IV hosp module
dfs_hosp = {}
dfs_hosp = read_folder(dfs_hosp, mimiciv_hosp_path)

Read files in folder C:\Users\qx398\MIMICWorkspace\MIMIC-IV-Parquet\physionet.org\files\mimiciv\3.1\hosp

100%|██████████| 22/22 [01:51<00:00,  5.05s/it]

In [4]:
# MIMIC-IV icu module
dfs_icu = {}
# Read large dataframes into pandas dataframe since computing such dask dataframe requires a great amount of time and memory
# dfs_icu['chartevents'] = pd.read_csv(mimiciv_icu_path+'chartevents.csv.gz', compression='gzip')
# dfs_icu['chartevents'] = pd.read_parquet(
#     mimiciv_icu_path / 'chartevents.parquet'
# )
dfs_icu = read_folder(dfs_icu,mimiciv_icu_path)

Read files in folder C:\Users\qx398\MIMICWorkspace\MIMIC-IV-Parquet\physionet.org\files\mimiciv\3.1\icu

100%|██████████| 9/9 [01:44<00:00, 11.64s/it]

In [5]:
# MIMIC-IV-CXR
dfs_cxr = {}
dfs_cxr = read_folder(dfs_cxr, mimiciv_cxr_path)
dfs_cxr_jpg = {}
dfs_cxr_jpg = read_folder(dfs_cxr_jpg, mimiciv_cxr_jpg_path)

Read files in folder C:\Users\qx398\MIMICWorkspace\MIMIC-CXR\2.1.0

100%|██████████| 7/7 [00:01<00:00,  4.45it/s]

Read files in folder C:\Users\qx398\MIMICWorkspace\mimic-cxr-jpg\2.1.0

100%|██████████| 10/10 [00:02<00:00,  4.17it/s]

In [6]:
# MIMIC-IV-Notes
dfs_note = {}
dfs_note = read_folder(dfs_note, mimiciv_note_path)

Read files in folder C:\Users\qx398\MIMICWorkspace\MIMIC-IV-Note-Parquet\mimic-iv-note-deidentified-free-text-clinical-notes-2.2\note

100%|██████████| 4/4 [00:13<00:00,  3.42s/it]

### datetime conversion

In [7]:
# Hosp
dfs_hosp = convert_datetime(dfs_hosp)
# ICU
dfs_icu = convert_datetime(dfs_icu)
# Note
dfs_note = convert_datetime(dfs_note)

In [8]:
# convert time-related variables in CXR metadata
dfs_cxr_jpg['mimic-cxr-2.0.0-metadata'] = dfs_cxr_jpg['mimic-cxr-2.0.0-metadata'].compute()
df = dfs_cxr_jpg['mimic-cxr-2.0.0-metadata']
df['StudyDate'] = df['StudyDate'].astype('int')
df['StudyDate'] = pd.to_datetime(df['StudyDate'],format='%Y%m%d')
df['StudyTime'] = df.apply(lambda x : '%#010.3f' % x['StudyTime'] ,1)
df['StudyTime'] = pd.to_datetime(df['StudyTime'], format='%H%M%S.%f').dt.strftime('%H%M%S')
df['StudyTime'] = pd.to_datetime(df['StudyTime'], format='%H%M%S').dt.time
df['StudyDatetime'] = df.apply(lambda r : dt.datetime.combine(r['StudyDate'],r['StudyTime']),1)

## ID combinations

### get ID lists from each module

In [9]:
## MIMIC-IV
dfs_hosp['admissions'] = dfs_hosp['admissions'].compute()
dfs_icu['icustays'] = dfs_icu['icustays'].compute()
## MIMIC-IV CXR
dfs_cxr['cxr-record-list'] = dfs_cxr['cxr-record-list'].compute()
## MIMIC-IV Note
dfs_note['discharge'] = dfs_note['discharge'].compute()
dfs_note['radiology'] = dfs_note['radiology'].compute()

In [10]:
# Get all combinations of IDs in ICU module
icu_info = dfs_icu['icustays'][['subject_id','hadm_id','stay_id','intime','outtime']].copy()
icu_info = icu_info.merge(dfs_hosp['admissions'][['subject_id','hadm_id','admittime','dischtime','edregtime','edouttime']],
                          on=['subject_id','hadm_id'],how='left')
icu_info['earliest_intime'] = icu_info[['intime','admittime','edregtime']].min(axis=1) # earliest entering time for each hospitalization
# Get all combination of IDs in CXR module
cxr_info = dfs_cxr_jpg['mimic-cxr-2.0.0-metadata'][['subject_id','study_id','dicom_id','StudyDate','StudyTime','StudyDatetime']].copy()
# Get all combinations of IDs in Note module
note_ds_info = dfs_note['discharge'][['note_id','subject_id','hadm_id','charttime']].copy()
note_ds_info.rename(columns={'note_id':'ds_note_id','charttime':'ds_charttime'},inplace=True)
note_rad_info = dfs_note['radiology'][['note_id','subject_id','hadm_id','charttime']].copy()
note_rad_info.rename(columns={'note_id':'rad_note_id','charttime':'rad_charttime'},inplace=True)

### merge IDs by key identifiers and time

In [11]:
pysqldf = lambda q: sqldf(q, globals())

In [12]:
# For radiology reports and chest X-ray, we combine the data also by time

## Join on MIMIC-IV,MIMIC-CXR and MIMICIV-Note
sql_query = """
select distinct key_subject_id as subject_id,key_hadm_id as hadm_id,stay_id,study_id,dicom_id,ds_note_id,rad_note_id
from 
(
    select subject_id as key_subject_id,hadm_id as key_hadm_id,stay_id,intime,outtime,admittime,dischtime,earliest_intime
    from icu_info
) as i
left join cxr_info c
on i.key_subject_id = c.subject_id and c.StudyDatetime >= i.earliest_intime and c.StudyDatetime <= i.outtime
left join note_ds_info ds
on i.key_subject_id = ds.subject_id and i.key_hadm_id = ds.hadm_id
left join note_rad_info rad
on i.key_subject_id = rad.subject_id and i.key_hadm_id = rad.hadm_id and rad.rad_charttime >= i.earliest_intime and rad.rad_charttime <= i.outtime
"""
list_ids = pysqldf(sql_query)

# save the list of IDs for generating master dataset
# Parquet — smaller on disk, preserves dtypes, faster to reload for large tables
list_ids.to_parquet("list_ids.parquet", index=False)  # needs: pip install pyarrow --break-system-packages

In [13]:
# load the list of IDs for generating master dataset
list_ids = pd.read_parquet("list_ids.parquet")

# verify the loaded data
print(list_ids.shape[0])  # number of rows
print(list_ids.columns.tolist())  # column names

2155802
['subject_id', 'hadm_id', 'stay_id', 'study_id', 'dicom_id', 'ds_note_id', 'rad_note_id']

In [14]:
# key identifiers
key_ids = list_ids[['subject_id','hadm_id','stay_id']].drop_duplicates().reset_index(drop=True)
key_ids

       subject_id   hadm_id   stay_id
0        10000032  29079034  39553978
1        10000690  25860671  37081114
2        10000980  26913865  39765666
3        10001217  24597018  37067082
4        10001217  27703517  34592300
...           ...       ...       ...
94453    19999442  26785317  32336619
94454    19999625  25304202  31070865
94455    19999828  25744818  36075953
94456    19999840  21033226  38978960
94457    19999987  23865745  36195440

[94458 rows x 3 columns]

### summary

In [15]:
print('For patients admitted to ICU')
print('Number of unique patients:',list_ids['subject_id'].nunique())
print('Number of unique hospital admissions:',list_ids['hadm_id'].nunique())
print('Number of unique ICU stays:',list_ids['stay_id'].nunique())
print('Number of unique chest xray studies:',list_ids['study_id'].nunique())
print('Number of unique chest xray images:',list_ids['dicom_id'].nunique())
print('Number of unique discharge summaries:',list_ids['ds_note_id'].nunique())
print('Number of unique radiology reports:',list_ids['rad_note_id'].nunique())

For patients admitted to ICU
Number of unique patients: 65366
Number of unique hospital admissions: 85242
Number of unique ICU stays: 94458
Number of unique chest xray studies: 72174
Number of unique chest xray images: 86654
Number of unique discharge summaries: 65323
Number of unique radiology reports: 412628

## Extract information for each unique ICU stay

### functions

In [16]:
import time

# Get full MIMIC-IV patient records using key_identifiers
def get_patient_icustay(key_subject_id, key_hadm_id, key_stay_id):
    """
    Inputs:
    key_subject_id -> subject_id is unique to a patient
    key_hadm_id    -> hadm_id is unique to a patient hospital stay
    key_stay_id    -> stay_id is unique to a patient ward stay
    Outputs:
    Patient_ICUstay -> ICU patient stay structure
    """
    # Data Extraction

    # debugging
    start = time.time()
    
    ## Table of identifiers
    df_core = list_ids[(list_ids.subject_id == key_subject_id) & (list_ids.hadm_id == key_hadm_id) & 
                       (list_ids.stay_id == key_stay_id)]
    
    ## Hosp - Tables are merged based on subject_id & hadm_id
    # Since miscellaneous information in OMR table is less detailed than in chartevents table, 
    # thus information from OMR table will not be included
    df_admissions = dfs_hosp['admissions'][(dfs_hosp['admissions'].subject_id == key_subject_id) & 
                                           (dfs_hosp['admissions'].hadm_id == key_hadm_id)]
    df_patients = dfs_hosp['patients'][(dfs_hosp['patients'].subject_id == key_subject_id)]
    df_transfers = dfs_hosp['transfers'][(dfs_hosp['transfers'].subject_id == key_subject_id) & 
                                         (dfs_hosp['transfers'].hadm_id == key_hadm_id)]
    df_diagnoses_icd = dfs_hosp['diagnoses_icd'][(dfs_hosp['diagnoses_icd'].subject_id == key_subject_id) &
                                                 (dfs_hosp['diagnoses_icd'].hadm_id == key_hadm_id)]
    df_diagnoses_icd = df_diagnoses_icd.merge(dfs_hosp['d_icd_diagnoses'],
                                              how='left', on=['icd_code', 'icd_version'])
    df_procedures_icd = dfs_hosp['procedures_icd'][(dfs_hosp['procedures_icd'].subject_id == key_subject_id) & 
                                                   (dfs_hosp['procedures_icd'].hadm_id == key_hadm_id)]
    df_procedures_icd = df_procedures_icd.merge(dfs_hosp['d_icd_procedures'], 
                                                how='left', on=['icd_code', 'icd_version'])
    df_drgcodes = dfs_hosp['drgcodes'][(dfs_hosp['drgcodes'].subject_id == key_subject_id) & 
                                       (dfs_hosp['drgcodes'].hadm_id == key_hadm_id)]
    df_services = dfs_hosp['services'][(dfs_hosp['services'].subject_id == key_subject_id) & 
                                       (dfs_hosp['services'].hadm_id == key_hadm_id)]
    df_labevents = dfs_hosp['labevents'][(dfs_hosp['labevents'].subject_id == key_subject_id) & 
                                         (dfs_hosp['labevents'].hadm_id == key_hadm_id)]
    df_labevents = df_labevents.merge(dfs_hosp['d_labitems'], how='left',on='itemid')
    df_hcpcsevents = dfs_hosp['hcpcsevents'][(dfs_hosp['hcpcsevents'].subject_id == key_subject_id) & 
                                             (dfs_hosp['hcpcsevents'].hadm_id == key_hadm_id)]
    df_hcpcsevents = df_hcpcsevents.merge(dfs_hosp['d_hcpcs'], how='left',
                                          left_on='hcpcs_cd',right_on='code')
    df_microbiologyevents = dfs_hosp['microbiologyevents'][(dfs_hosp['microbiologyevents'].subject_id == key_subject_id) & 
                                                           (dfs_hosp['microbiologyevents'].hadm_id == key_hadm_id)]
    df_emar = dfs_hosp['emar'][(dfs_hosp['emar'].subject_id == key_subject_id) & 
                               (dfs_hosp['emar'].hadm_id == key_hadm_id)]
    df_emar = df_emar.merge(dfs_hosp['emar_detail'], how='left', on='emar_id' )
    df_poe = dfs_hosp['poe'][(dfs_hosp['poe'].subject_id == key_subject_id) & (dfs_hosp['poe'].hadm_id == key_hadm_id)]
    df_poe = df_poe.merge(dfs_hosp['poe_detail'], how='left', on='poe_id')
    df_prescriptions = dfs_hosp['prescriptions'][(dfs_hosp['prescriptions'].subject_id == key_subject_id) & 
                                                 (dfs_hosp['prescriptions'].hadm_id == key_hadm_id)]
    df_prescriptions = df_prescriptions.merge(dfs_hosp['pharmacy'], how='left', on='pharmacy_id')
    
    ## ICU - Tables are merged based on subject_id & hadm_id & stay_id
    df_icustays = dfs_icu['icustays'][(dfs_icu['icustays'].subject_id == key_subject_id) & 
                                      (dfs_icu['icustays'].hadm_id == key_hadm_id) & 
                                      (dfs_icu['icustays'].stay_id == key_stay_id)]
    df_procedureevents = dfs_icu['procedureevents'][(dfs_icu['procedureevents'].subject_id == key_subject_id) & 
                                                    (dfs_icu['procedureevents'].hadm_id == key_hadm_id) & 
                                                    (dfs_icu['procedureevents'].stay_id == key_stay_id)]
    df_outputevents = dfs_icu['outputevents'][(dfs_icu['outputevents'].subject_id == key_subject_id) & 
                                              (dfs_icu['outputevents'].hadm_id == key_hadm_id) & 
                                              (dfs_icu['outputevents'].stay_id == key_stay_id)]
    df_inputevents = dfs_icu['inputevents'][(dfs_icu['inputevents'].subject_id == key_subject_id) & 
                                            (dfs_icu['inputevents'].hadm_id == key_hadm_id) & 
                                            (dfs_icu['inputevents'].stay_id == key_stay_id)]
    df_datetimeevents = dfs_icu['datetimeevents'][(dfs_icu['datetimeevents'].subject_id == key_subject_id) & 
                                                  (dfs_icu['datetimeevents'].hadm_id == key_hadm_id) & 
                                                  (dfs_icu['datetimeevents'].stay_id == key_stay_id)]


    df_chartevents = dfs_icu['chartevents'][(dfs_icu['chartevents'].subject_id == key_subject_id) & 
                                            (dfs_icu['chartevents'].hadm_id == key_hadm_id) & 
                                            (dfs_icu['chartevents'].stay_id == key_stay_id)]
    
    df_ingredientevents = dfs_icu['ingredientevents'][(dfs_icu['ingredientevents'].subject_id == key_subject_id) & 
                                                      (dfs_icu['ingredientevents'].hadm_id == key_hadm_id) & 
                                                      (dfs_icu['ingredientevents'].stay_id == key_stay_id)]

    # debugging
    # print("hosp, icu filtering finished", time.time()-start)
    # start=time.time()

    # Merge descriptions into each table
    df_procedureevents = df_procedureevents.merge(dfs_icu['d_items'], how='left', on='itemid')
    df_outputevents = df_outputevents.merge(dfs_icu['d_items'], how='left', on='itemid')
    df_inputevents = df_inputevents.merge(dfs_icu['d_items'], how='left', on='itemid')
    df_datetimeevents = df_datetimeevents.merge(dfs_icu['d_items'], how='left', on='itemid')
    df_chartevents = df_chartevents.merge(dfs_icu['d_items'], how='left', on='itemid')
    df_ingredientevents = df_ingredientevents.merge(dfs_icu['d_items'], how='left', on='itemid')

    # debugging
    # print("hosp, icu merge finished:", time.time()-start)
    # start=time.time()

    ## CXR
    # Get lists of study_id and dicom_id for each ICU stay
    study_id_list = df_core['study_id'].unique()
    dicom_id_list = df_core['dicom_id'].unique()
    # Extract tables from MIMIC-CXR
    df_cxr_image_path = dfs_cxr['cxr-record-list'][(dfs_cxr['cxr-record-list'].subject_id == key_subject_id) &
                                                   (dfs_cxr['cxr-record-list'].study_id.isin(study_id_list)) &
                                                   (dfs_cxr['cxr-record-list'].dicom_id.isin(dicom_id_list))]
    df_cxr_text_path = dfs_cxr['cxr-study-list'][(dfs_cxr['cxr-study-list'].subject_id == key_subject_id) &
                                                   (dfs_cxr['cxr-study-list'].study_id.isin(study_id_list))]

    # debugging
    # print("CXR finished:", time.time()-start)
    # start=time.time()

    # Extract tables from MIMIC-CXR-JPG
    df_cxr_metadata = dfs_cxr_jpg['mimic-cxr-2.0.0-metadata'][(dfs_cxr_jpg['mimic-cxr-2.0.0-metadata'].subject_id == key_subject_id) &
                                                              (dfs_cxr_jpg['mimic-cxr-2.0.0-metadata'].study_id.isin(study_id_list)) &
                                                              (dfs_cxr_jpg['mimic-cxr-2.0.0-metadata'].dicom_id.isin(dicom_id_list))]
    df_cxr_chexpert = dfs_cxr_jpg['mimic-cxr-2.0.0-chexpert'][(dfs_cxr_jpg['mimic-cxr-2.0.0-chexpert'].subject_id == key_subject_id) &
                                                              (dfs_cxr_jpg['mimic-cxr-2.0.0-chexpert'].study_id.isin(study_id_list))]
    df_cxr_negbio = dfs_cxr_jpg['mimic-cxr-2.0.0-negbio'][(dfs_cxr_jpg['mimic-cxr-2.0.0-negbio'].subject_id == key_subject_id) & 
                                                          (dfs_cxr_jpg['mimic-cxr-2.0.0-negbio'].study_id.isin(study_id_list))]
    df_cxr_split = dfs_cxr_jpg['mimic-cxr-2.0.0-split'][(dfs_cxr_jpg['mimic-cxr-2.0.0-split'].subject_id == key_subject_id) &
                                                        (dfs_cxr_jpg['mimic-cxr-2.0.0-split'].study_id.isin(study_id_list)) &
                                                        (dfs_cxr_jpg['mimic-cxr-2.0.0-split'].dicom_id.isin(dicom_id_list))]

    # debugging
    # print("CXR-JPG finished:", time.time()-start)
    # start=time.time()

    ## Notes
    ds_note_id_list = df_core['ds_note_id'].unique()
    rad_note_id_list = df_core['rad_note_id'].unique()   

    # original code for notes extraction, which is slow

    # df_dsnotes = dfs_note['discharge'][(dfs_note['discharge'].subject_id == key_subject_id) &
    #                                    (dfs_note['discharge'].hadm_id == key_hadm_id) &
    #                                    (dfs_note['discharge'].note_id.isin(ds_note_id_list))]
    # df_radnotes = dfs_note['radiology'][(dfs_note['radiology'].subject_id == key_subject_id) &
    #                                     (dfs_note['radiology'].hadm_id == key_hadm_id) &
    #                                     (dfs_note['radiology'].note_id.isin(rad_note_id_list))]
    # debugging
    # print("ORIGINAL: Notes loading finished:", time.time()-start)
    # start=time.time()

    # performance optimization: set index and sort index for faster data retrieval

    # try:
    #     df_dsnotes = dfs_note['discharge'].loc[(key_subject_id,key_hadm_id)]

    #     # if single row, convert back to dataframe
    #     if isinstance(df_dsnotes, pd.Series):
    #         df_dsnotes = df_dsnotes.to_frame().T

    # except KeyError:
    #     df_dsnotes = dfs_note['discharge'].iloc[0:0].reset_index()
    # try:
    #     df_radnotes = dfs_note['radiology'].loc[(key_subject_id,key_hadm_id)]

    #     # if single row, convert back to dataframe
    #     if isinstance(df_radnotes, pd.Series):
    #         df_radnotes = df_radnotes.to_frame().T

    # except KeyError:
    #     df_radnotes = dfs_note['radiology'].iloc[0:0].reset_index()  

    try:
        df_dsnotes = dfs_note['discharge'].loc[[(key_subject_id, key_hadm_id)]].reset_index()
    except KeyError:
        df_dsnotes = dfs_note['discharge'].iloc[0:0].reset_index()
    df_dsnotes = df_dsnotes[df_dsnotes.note_id.isin(ds_note_id_list)]

    try:
        df_radnotes = dfs_note['radiology'].loc[[(key_subject_id, key_hadm_id)]].reset_index()
    except KeyError:
        df_radnotes = dfs_note['radiology'].iloc[0:0].reset_index()
    df_radnotes = df_radnotes[df_radnotes.note_id.isin(rad_note_id_list)]

    # debugging
    # print(df_radnotes.head())
    # print(df_radnotes.columns)
    # print(df_radnotes.index)
    
     # debugging
    # print("Optimized:Notes loading finished:", time.time()-start)
    # start=time.time()

    # df_radnotes = df_radnotes.merge(dfs_note['radiology_detail'], how='left', on='note_id')
    # if len(df_radnotes) > 0:
    #     df_radnotes = df_radnotes.merge(
    #         dfs_note['radiology_detail'],
    #         how='left',
    #         on='note_id'
    #     )   

    if len(df_radnotes) > 0:
        df_radnotes = df_radnotes.merge(dfs_note['radiology_detail'], how='left', on='note_id')    

    # debugging
    # print(f"Notes merge finished: {time.time()-start:.2f}s")
    # start = time.time()

    # Create patient object and return
    Patient_ICUstay = Patient_ICU(df_core, df_admissions, df_patients, df_transfers, df_diagnoses_icd, df_procedures_icd, df_drgcodes,
                                  df_services, df_labevents, df_hcpcsevents, df_microbiologyevents, df_emar, df_poe, df_prescriptions, 
                                  df_icustays, df_procedureevents, df_outputevents, df_inputevents, df_datetimeevents, df_chartevents, df_ingredientevents,
                                  df_cxr_split, df_cxr_metadata, df_cxr_chexpert, df_cxr_negbio, df_cxr_image_path, df_cxr_text_path, 
                                  df_dsnotes, df_radnotes)

    # debugging
    # print(f"Patient_ICU finished: {time.time()-start:.2f}s")
     
    return Patient_ICUstay

In [17]:
import time

# Extract all single ICU stay records
def generate_master_dataset(key_ids, storage_path):
    # Inputs:
    #   key_ids -> Dataframe with all unique available records by key identifiers
    #   storage_path -> Path to structured MIMIC IV databases in pickle files
    
    # Outputs:
    #   nfiles -> Number of single patient files produced
    
    # Extract information for patient
    nfiles = len(key_ids)
    with tqdm(total = nfiles) as pbar:

        #Iterate through all patients

        # ORIGINAL CODE very slow        
        # for _, content in key_ids.iterrows():

        #     # debugging
        #     start = time.time()

        #     key_subject_id = content['subject_id']
        #     key_hadm_id = content['hadm_id']
        #     key_stay_id = content['stay_id']
            
        #     # Save objects
        #     filename = f'ICUstay_{int(key_stay_id)}'+'.pkl'
        #     icustay = get_patient_icustay(key_subject_id,key_hadm_id,key_stay_id)

        #     # debugging
        #     print(f"get_patient_icustay: {time.time()-start:.2f}s")
        #     start = time.time()

        #     # pickle.dump(icustay,open(storage_path+filename,'wb'))
        #     pickle.dump(icustay,open(storage_path / filename,'wb'))

        #     # debugging
        #     print(f"pickle: {time.time()-start:.2f}s")

        #     # Update process bar
        #     pbar.update(1)

        # Optimization: speed up the process
        for row in key_ids.itertuples(index=False):

            # debugging
            start = time.time()

            key_subject_id = row.subject_id
            key_hadm_id = row.hadm_id
            key_stay_id = row.stay_id
            
            # Save objects
            filename = f'ICUstay_{int(key_stay_id)}'+'.pkl'
            icustay = get_patient_icustay(key_subject_id,key_hadm_id,key_stay_id)

            # debugging
            print(f"get_patient_icustay: {time.time()-start:.2f}s")
            # start = time.time()

            # pickle.dump(icustay,open(storage_path+filename,'wb'))
            pickle.dump(icustay,open(storage_path / filename,'wb'))

            # debugging
            # print(f"pickle: {time.time()-start:.2f}s")

            # Update process bar
            pbar.update(1)

### extract and save patient ICU stay information

In [18]:
dfs_icu['d_items'] = dfs_icu['d_items'].compute()
dfs_note['radiology_detail'] = dfs_note['radiology_detail'].compute()

In [19]:
# debugging
print(type(dfs_note['radiology']))
print(type(dfs_note['discharge']))

print(dfs_note['radiology'].shape)
print(dfs_note['discharge'].shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(2321355, 8)
(331793, 8)

In [20]:
# performance optimization: set index and sort index for faster data retrieval
dfs_note['discharge'] = dfs_note['discharge'].set_index(
    ['subject_id','hadm_id']
).sort_index() 
dfs_note['radiology'] = dfs_note['radiology'].set_index(
    ['subject_id','hadm_id']
).sort_index()

In [21]:
ICU_path = Path('~/MIMICWorkspace/MasterDataset/').expanduser()

# debugging
# generate_master_dataset(key_ids=key_ids[0:10],storage_path=ICU_path)

# production part1 ID 0 ~ 30000
# generate_master_dataset(key_ids=key_ids[0:30000],storage_path=ICU_path)

# Aug 3 Continue from breakpoint, ID 9278 ~ 30000
# generate_master_dataset(key_ids=key_ids[9278:30000],storage_path=ICU_path)

In [22]:
# production part1 ID 30000 ~
# generate_master_dataset(key_ids=key_ids[30000:],storage_path=ICU_path)
generate_master_dataset(key_ids=key_ids[94029:],storage_path=ICU_path)

  0%|          | 0/429 [00:00<?, ?it/s]

get_patient_icustay: 7.45s

  0%|          | 2/429 [00:11<40:16,  5.66s/it]

get_patient_icustay: 4.03s

  1%|          | 3/429 [00:15<34:16,  4.83s/it]

get_patient_icustay: 3.70s

  1%|          | 4/429 [00:19<32:21,  4.57s/it]

get_patient_icustay: 4.11s

  1%|          | 5/429 [00:23<30:27,  4.31s/it]

get_patient_icustay: 3.78s

  1%|▏         | 6/429 [00:27<29:40,  4.21s/it]

get_patient_icustay: 3.89s

  2%|▏         | 7/429 [00:31<29:25,  4.18s/it]

get_patient_icustay: 4.07s

  2%|▏         | 8/429 [00:32<21:23,  3.05s/it]

get_patient_icustay: 0.55s

  2%|▏         | 9/429 [00:33<16:11,  2.31s/it]

get_patient_icustay: 0.55s

  2%|▏         | 10/429 [00:37<19:35,  2.80s/it]

get_patient_icustay: 3.84s

  3%|▎         | 11/429 [00:37<14:39,  2.10s/it]

get_patient_icustay: 0.45s

  3%|▎         | 12/429 [00:41<17:59,  2.59s/it]

get_patient_icustay: 3.64s

  3%|▎         | 13/429 [00:45<21:16,  3.07s/it]

get_patient_icustay: 4.11s

  3%|▎         | 14/429 [00:49<23:05,  3.34s/it]

get_patient_icustay: 3.84s

  3%|▎         | 15/429 [00:50<17:10,  2.49s/it]

get_patient_icustay: 0.46s

  4%|▎         | 16/429 [00:50<13:14,  1.92s/it]

get_patient_icustay: 0.53s

  4%|▍         | 17/429 [00:51<10:30,  1.53s/it]

get_patient_icustay: 0.56s

  4%|▍         | 18/429 [00:55<14:56,  2.18s/it]

get_patient_icustay: 3.56s

  4%|▍         | 19/429 [00:59<19:04,  2.79s/it]

get_patient_icustay: 4.09s

  5%|▍         | 20/429 [00:59<14:29,  2.13s/it]

get_patient_icustay: 0.51s

  5%|▍         | 21/429 [01:03<17:38,  2.59s/it]

get_patient_icustay: 3.62s

  5%|▌         | 22/429 [01:07<20:03,  2.96s/it]

get_patient_icustay: 3.74s

  5%|▌         | 23/429 [01:10<21:26,  3.17s/it]

get_patient_icustay: 3.60s

  6%|▌         | 24/429 [01:11<16:15,  2.41s/it]

get_patient_icustay: 0.53s

  6%|▌         | 25/429 [01:15<18:39,  2.77s/it]

get_patient_icustay: 3.56s

  6%|▌         | 26/429 [01:18<20:21,  3.03s/it]

get_patient_icustay: 3.57s

  6%|▋         | 27/429 [01:19<15:26,  2.30s/it]

get_patient_icustay: 0.49s

  7%|▋         | 28/429 [01:19<11:50,  1.77s/it]

get_patient_icustay: 0.46s

  7%|▋         | 29/429 [01:20<09:23,  1.41s/it]

get_patient_icustay: 0.50s

  7%|▋         | 30/429 [01:24<14:28,  2.18s/it]

get_patient_icustay: 3.86s

  7%|▋         | 31/429 [01:28<17:35,  2.65s/it]

get_patient_icustay: 3.70s

  7%|▋         | 32/429 [01:28<13:17,  2.01s/it]

get_patient_icustay: 0.45s

  8%|▊         | 33/429 [01:32<16:50,  2.55s/it]

get_patient_icustay: 3.71s

  8%|▊         | 34/429 [01:36<19:13,  2.92s/it]

get_patient_icustay: 3.71s

  8%|▊         | 35/429 [01:39<20:28,  3.12s/it]

get_patient_icustay: 3.52s

  8%|▊         | 36/429 [01:43<21:32,  3.29s/it]

get_patient_icustay: 3.57s

  9%|▊         | 37/429 [01:47<22:10,  3.39s/it]

get_patient_icustay: 3.58s

  9%|▉         | 38/429 [01:50<22:38,  3.47s/it]

get_patient_icustay: 3.54s

  9%|▉         | 39/429 [01:54<22:48,  3.51s/it]

get_patient_icustay: 3.53s

  9%|▉         | 40/429 [01:58<22:57,  3.54s/it]

get_patient_icustay: 3.55s

 10%|▉         | 41/429 [02:01<23:12,  3.59s/it]

get_patient_icustay: 3.58s

 10%|▉         | 42/429 [02:05<23:24,  3.63s/it]

get_patient_icustay: 3.66s

 10%|█         | 43/429 [02:09<23:09,  3.60s/it]

get_patient_icustay: 3.47s

 10%|█         | 44/429 [02:09<17:18,  2.70s/it]

get_patient_icustay: 0.48s

 10%|█         | 45/429 [02:10<13:15,  2.07s/it]

get_patient_icustay: 0.54s

 11%|█         | 46/429 [02:13<16:04,  2.52s/it]

get_patient_icustay: 3.50s

 11%|█         | 47/429 [02:17<18:15,  2.87s/it]

get_patient_icustay: 3.62s

 11%|█         | 48/429 [02:21<19:31,  3.07s/it]

get_patient_icustay: 3.49s

 11%|█▏        | 49/429 [02:21<14:46,  2.33s/it]

get_patient_icustay: 0.49s

 12%|█▏        | 50/429 [02:25<17:01,  2.69s/it]

get_patient_icustay: 3.48s

 12%|█▏        | 51/429 [02:28<18:32,  2.94s/it]

get_patient_icustay: 3.46s

 12%|█▏        | 52/429 [02:32<19:49,  3.16s/it]

get_patient_icustay: 3.53s

 12%|█▏        | 53/429 [02:32<14:53,  2.38s/it]

get_patient_icustay: 0.49s

 13%|█▎        | 54/429 [02:36<17:08,  2.74s/it]

get_patient_icustay: 3.54s

 13%|█▎        | 55/429 [02:40<18:48,  3.02s/it]

get_patient_icustay: 3.54s

 13%|█▎        | 56/429 [02:40<14:08,  2.27s/it]

get_patient_icustay: 0.48s

 13%|█▎        | 57/429 [02:44<16:37,  2.68s/it]

get_patient_icustay: 3.56s

 14%|█▎        | 58/429 [02:48<18:19,  2.96s/it]

get_patient_icustay: 3.50s

 14%|█▍        | 59/429 [02:51<19:26,  3.15s/it]

get_patient_icustay: 3.54s

 14%|█▍        | 60/429 [02:55<20:03,  3.26s/it]

get_patient_icustay: 3.45s

 14%|█▍        | 61/429 [02:58<20:41,  3.37s/it]

get_patient_icustay: 3.52s

 14%|█▍        | 62/429 [02:59<15:23,  2.52s/it]

get_patient_icustay: 0.45s

 15%|█▍        | 63/429 [03:02<17:20,  2.84s/it]

get_patient_icustay: 3.54s

 15%|█▍        | 64/429 [03:06<18:45,  3.08s/it]

get_patient_icustay: 3.52s

 15%|█▌        | 65/429 [03:10<19:47,  3.26s/it]

get_patient_icustay: 3.62s

 15%|█▌        | 66/429 [03:13<20:18,  3.36s/it]

get_patient_icustay: 3.52s

 16%|█▌        | 67/429 [03:17<20:52,  3.46s/it]

get_patient_icustay: 3.64s

 16%|█▌        | 68/429 [03:21<21:01,  3.49s/it]

get_patient_icustay: 3.51s

 16%|█▌        | 69/429 [03:24<21:20,  3.56s/it]

get_patient_icustay: 3.58s

 16%|█▋        | 70/429 [03:28<21:29,  3.59s/it]

get_patient_icustay: 3.62s

 17%|█▋        | 71/429 [03:32<21:30,  3.60s/it]

get_patient_icustay: 3.57s

 17%|█▋        | 72/429 [03:32<16:10,  2.72s/it]

get_patient_icustay: 0.52s

 17%|█▋        | 73/429 [03:33<12:18,  2.07s/it]

get_patient_icustay: 0.50s

 17%|█▋        | 74/429 [03:33<09:31,  1.61s/it]

get_patient_icustay: 0.46s

 17%|█▋        | 75/429 [03:37<13:41,  2.32s/it]

get_patient_icustay: 3.92s

 18%|█▊        | 76/429 [03:41<16:26,  2.79s/it]

get_patient_icustay: 3.83s

 18%|█▊        | 77/429 [03:45<17:57,  3.06s/it]

get_patient_icustay: 3.55s

 18%|█▊        | 78/429 [03:49<18:59,  3.25s/it]

get_patient_icustay: 3.62s

 18%|█▊        | 79/429 [03:52<19:28,  3.34s/it]

get_patient_icustay: 3.50s

 19%|█▊        | 80/429 [03:56<20:19,  3.49s/it]

get_patient_icustay: 3.72s

 19%|█▉        | 81/429 [04:00<20:56,  3.61s/it]

get_patient_icustay: 3.81s

 19%|█▉        | 82/429 [04:04<21:31,  3.72s/it]

get_patient_icustay: 3.91s

 19%|█▉        | 83/429 [04:08<21:51,  3.79s/it]

get_patient_icustay: 3.83s

 20%|█▉        | 84/429 [04:08<16:13,  2.82s/it]

get_patient_icustay: 0.51s

 20%|█▉        | 85/429 [04:12<17:35,  3.07s/it]

get_patient_icustay: 3.58s

 20%|██        | 86/429 [04:16<18:20,  3.21s/it]

get_patient_icustay: 3.42s

 20%|██        | 87/429 [04:19<18:54,  3.32s/it]

get_patient_icustay: 3.51s

 21%|██        | 88/429 [04:23<19:24,  3.41s/it]

get_patient_icustay: 3.58s

 21%|██        | 89/429 [04:26<19:47,  3.49s/it]

get_patient_icustay: 3.61s

 21%|██        | 90/429 [04:30<19:54,  3.52s/it]

get_patient_icustay: 3.54s

 21%|██        | 91/429 [04:31<14:51,  2.64s/it]

get_patient_icustay: 0.46s

 21%|██▏       | 92/429 [04:31<11:20,  2.02s/it]

get_patient_icustay: 0.50s

 22%|██▏       | 93/429 [04:32<08:40,  1.55s/it]

get_patient_icustay: 0.39s

 22%|██▏       | 94/429 [04:32<07:02,  1.26s/it]

get_patient_icustay: 0.45s

 22%|██▏       | 95/429 [04:36<10:51,  1.95s/it]

get_patient_icustay: 3.51s

 22%|██▏       | 96/429 [04:39<13:42,  2.47s/it]

get_patient_icustay: 3.62s

 23%|██▎       | 97/429 [04:43<15:31,  2.80s/it]

get_patient_icustay: 3.52s

 23%|██▎       | 98/429 [04:47<16:57,  3.07s/it]

get_patient_icustay: 3.64s

 23%|██▎       | 99/429 [04:47<12:46,  2.32s/it]

get_patient_icustay: 0.51s

 23%|██▎       | 100/429 [04:51<14:53,  2.72s/it]

get_patient_icustay: 3.52s

 24%|██▎       | 101/429 [04:55<16:22,  3.00s/it]

get_patient_icustay: 3.58s

 24%|██▍       | 102/429 [04:58<17:08,  3.15s/it]

get_patient_icustay: 3.44s

 24%|██▍       | 103/429 [05:02<17:55,  3.30s/it]

get_patient_icustay: 3.54s

 24%|██▍       | 104/429 [05:05<18:19,  3.38s/it]

get_patient_icustay: 3.52s

 24%|██▍       | 105/429 [05:06<13:42,  2.54s/it]

get_patient_icustay: 0.51s

 25%|██▍       | 106/429 [05:06<10:29,  1.95s/it]

get_patient_icustay: 0.45s

 25%|██▍       | 107/429 [05:07<08:10,  1.52s/it]

get_patient_icustay: 0.47s

 25%|██▌       | 108/429 [05:11<11:31,  2.16s/it]

get_patient_icustay: 3.56s

 25%|██▌       | 109/429 [05:11<08:56,  1.68s/it]

get_patient_icustay: 0.44s

 26%|██▌       | 110/429 [05:15<12:04,  2.27s/it]

get_patient_icustay: 3.59s

 26%|██▌       | 111/429 [05:19<14:16,  2.69s/it]

get_patient_icustay: 3.56s

 26%|██▌       | 112/429 [05:19<10:52,  2.06s/it]

get_patient_icustay: 0.51s

 26%|██▋       | 113/429 [05:23<13:14,  2.51s/it]

get_patient_icustay: 3.52s

 27%|██▋       | 114/429 [05:26<15:08,  2.88s/it]

get_patient_icustay: 3.63s

 27%|██▋       | 115/429 [05:30<16:13,  3.10s/it]

get_patient_icustay: 3.55s

 27%|██▋       | 116/429 [05:31<12:12,  2.34s/it]

get_patient_icustay: 0.51s

 27%|██▋       | 117/429 [05:34<14:21,  2.76s/it]

get_patient_icustay: 3.63s

 28%|██▊       | 118/429 [05:38<15:41,  3.03s/it]

get_patient_icustay: 3.59s

 28%|██▊       | 119/429 [05:39<11:46,  2.28s/it]

get_patient_icustay: 0.46s

 28%|██▊       | 120/429 [05:39<09:12,  1.79s/it]

get_patient_icustay: 0.49s

 28%|██▊       | 121/429 [05:43<11:54,  2.32s/it]

get_patient_icustay: 3.50s

 28%|██▊       | 122/429 [05:43<09:06,  1.78s/it]

get_patient_icustay: 0.45s

 29%|██▊       | 123/429 [05:47<11:59,  2.35s/it]

get_patient_icustay: 3.56s

 29%|██▉       | 124/429 [05:51<13:50,  2.72s/it]

get_patient_icustay: 3.54s

 29%|██▉       | 125/429 [05:54<15:24,  3.04s/it]

get_patient_icustay: 3.66s

 29%|██▉       | 126/429 [05:58<16:04,  3.18s/it]

get_patient_icustay: 3.43s

 30%|██▉       | 127/429 [06:01<16:39,  3.31s/it]

get_patient_icustay: 3.55s

 30%|██▉       | 128/429 [06:05<17:01,  3.39s/it]

get_patient_icustay: 3.48s

 30%|███       | 129/429 [06:08<17:06,  3.42s/it]

get_patient_icustay: 3.43s

 30%|███       | 130/429 [06:12<17:22,  3.49s/it]

get_patient_icustay: 3.57s

 31%|███       | 131/429 [06:13<13:04,  2.63s/it]

get_patient_icustay: 0.52s

 31%|███       | 132/429 [06:13<09:55,  2.00s/it]

get_patient_icustay: 0.48s

 31%|███       | 133/429 [06:17<12:11,  2.47s/it]

get_patient_icustay: 3.49s

 31%|███       | 134/429 [06:21<13:52,  2.82s/it]

get_patient_icustay: 3.52s

 31%|███▏      | 135/429 [06:24<14:46,  3.01s/it]

get_patient_icustay: 3.41s

 32%|███▏      | 136/429 [06:28<15:44,  3.22s/it]

get_patient_icustay: 3.60s

 32%|███▏      | 137/429 [06:31<16:03,  3.30s/it]

get_patient_icustay: 3.41s

 32%|███▏      | 138/429 [06:35<16:32,  3.41s/it]

get_patient_icustay: 3.62s

 32%|███▏      | 139/429 [06:38<16:41,  3.45s/it]

get_patient_icustay: 3.50s

 33%|███▎      | 140/429 [06:42<16:50,  3.50s/it]

get_patient_icustay: 3.54s

 33%|███▎      | 141/429 [06:46<16:51,  3.51s/it]

get_patient_icustay: 3.49s

 33%|███▎      | 142/429 [06:49<17:02,  3.56s/it]

get_patient_icustay: 3.57s

 33%|███▎      | 143/429 [06:53<16:54,  3.55s/it]

get_patient_icustay: 3.45s

 34%|███▎      | 144/429 [06:56<16:50,  3.55s/it]

get_patient_icustay: 3.48s

 34%|███▍      | 145/429 [07:00<16:44,  3.54s/it]

get_patient_icustay: 3.40s

 34%|███▍      | 146/429 [07:03<16:45,  3.55s/it]

get_patient_icustay: 3.53s

 34%|███▍      | 147/429 [07:04<12:27,  2.65s/it]

get_patient_icustay: 0.48s

 34%|███▍      | 148/429 [07:08<13:53,  2.97s/it]

get_patient_icustay: 3.59s

 35%|███▍      | 149/429 [07:11<14:36,  3.13s/it]

get_patient_icustay: 3.44s

 35%|███▍      | 150/429 [07:15<15:15,  3.28s/it]

get_patient_icustay: 3.58s

 35%|███▌      | 151/429 [07:18<15:44,  3.40s/it]

get_patient_icustay: 3.55s

 35%|███▌      | 152/429 [07:19<11:45,  2.55s/it]

get_patient_icustay: 0.50s

 36%|███▌      | 153/429 [07:23<13:13,  2.87s/it]

get_patient_icustay: 3.53s

 36%|███▌      | 154/429 [07:26<14:16,  3.11s/it]

get_patient_icustay: 3.61s

 36%|███▌      | 155/429 [07:30<14:58,  3.28s/it]

get_patient_icustay: 3.61s

 36%|███▋      | 156/429 [07:34<15:26,  3.39s/it]

get_patient_icustay: 3.54s

 37%|███▋      | 157/429 [07:37<15:42,  3.47s/it]

get_patient_icustay: 3.58s

 37%|███▋      | 158/429 [07:41<16:06,  3.57s/it]

get_patient_icustay: 3.74s

 37%|███▋      | 159/429 [07:45<16:07,  3.59s/it]

get_patient_icustay: 3.51s

 37%|███▋      | 160/429 [07:48<16:07,  3.60s/it]

get_patient_icustay: 3.57s

 38%|███▊      | 161/429 [07:52<16:00,  3.58s/it]

get_patient_icustay: 3.49s

 38%|███▊      | 162/429 [07:56<16:05,  3.62s/it]

get_patient_icustay: 3.58s

 38%|███▊      | 163/429 [07:59<15:58,  3.60s/it]

get_patient_icustay: 3.50s

 38%|███▊      | 164/429 [08:00<11:50,  2.68s/it]

get_patient_icustay: 0.47s

 38%|███▊      | 165/429 [08:00<09:02,  2.06s/it]

get_patient_icustay: 0.48s

 39%|███▊      | 166/429 [08:01<07:01,  1.60s/it]

get_patient_icustay: 0.48s

 39%|███▉      | 167/429 [08:04<09:38,  2.21s/it]

get_patient_icustay: 3.56s

 39%|███▉      | 168/429 [08:08<11:30,  2.64s/it]

get_patient_icustay: 3.55s

 39%|███▉      | 169/429 [08:12<12:36,  2.91s/it]

get_patient_icustay: 3.47s

 40%|███▉      | 170/429 [08:15<13:17,  3.08s/it]

get_patient_icustay: 3.41s

 40%|███▉      | 171/429 [08:16<09:57,  2.32s/it]

get_patient_icustay: 0.48s

 40%|████      | 172/429 [08:19<11:36,  2.71s/it]

get_patient_icustay: 3.52s

 40%|████      | 173/429 [08:23<12:41,  2.98s/it]

get_patient_icustay: 3.52s

 41%|████      | 174/429 [08:27<13:31,  3.18s/it]

get_patient_icustay: 3.60s

 41%|████      | 175/429 [08:30<14:09,  3.34s/it]

get_patient_icustay: 3.66s

 41%|████      | 176/429 [08:31<10:33,  2.50s/it]

get_patient_icustay: 0.48s

 41%|████▏     | 177/429 [08:34<11:58,  2.85s/it]

get_patient_icustay: 3.52s

 41%|████▏     | 178/429 [08:39<13:51,  3.31s/it]

get_patient_icustay: 4.33s

 42%|████▏     | 179/429 [08:42<14:10,  3.40s/it]

get_patient_icustay: 3.55s

 42%|████▏     | 180/429 [08:46<14:26,  3.48s/it]

get_patient_icustay: 3.56s

 42%|████▏     | 181/429 [08:47<10:45,  2.60s/it]

get_patient_icustay: 0.49s

 42%|████▏     | 182/429 [08:50<12:05,  2.94s/it]

get_patient_icustay: 3.63s

 43%|████▎     | 183/429 [08:54<12:58,  3.17s/it]

get_patient_icustay: 3.65s

 43%|████▎     | 184/429 [08:58<13:52,  3.40s/it]

get_patient_icustay: 3.87s

 43%|████▎     | 185/429 [09:02<14:40,  3.61s/it]

get_patient_icustay: 3.97s

 43%|████▎     | 186/429 [09:06<14:40,  3.62s/it]

get_patient_icustay: 3.60s

 44%|████▎     | 187/429 [09:09<14:33,  3.61s/it]

get_patient_icustay: 3.52s

 44%|████▍     | 188/429 [09:13<14:40,  3.65s/it]

get_patient_icustay: 3.63s

 44%|████▍     | 189/429 [09:17<14:31,  3.63s/it]

get_patient_icustay: 3.52s

 44%|████▍     | 190/429 [09:20<14:26,  3.62s/it]

get_patient_icustay: 3.54s

 45%|████▍     | 191/429 [09:24<14:24,  3.63s/it]

get_patient_icustay: 3.53s

 45%|████▍     | 192/429 [09:28<14:20,  3.63s/it]

get_patient_icustay: 3.57s

 45%|████▍     | 193/429 [09:31<14:17,  3.63s/it]

get_patient_icustay: 3.58s

 45%|████▌     | 194/429 [09:32<10:40,  2.72s/it]

get_patient_icustay: 0.49s

 45%|████▌     | 195/429 [09:32<08:04,  2.07s/it]

get_patient_icustay: 0.46s

 46%|████▌     | 196/429 [09:33<06:15,  1.61s/it]

get_patient_icustay: 0.47s

 46%|████▌     | 197/429 [09:37<08:41,  2.25s/it]

get_patient_icustay: 3.68s

 46%|████▌     | 198/429 [09:40<10:18,  2.68s/it]

get_patient_icustay: 3.61s

 46%|████▋     | 199/429 [09:41<07:50,  2.05s/it]

get_patient_icustay: 0.46s

 47%|████▋     | 200/429 [09:44<09:35,  2.51s/it]

get_patient_icustay: 3.54s

 47%|████▋     | 201/429 [09:48<10:45,  2.83s/it]

get_patient_icustay: 3.51s

 47%|████▋     | 202/429 [09:52<11:39,  3.08s/it]

get_patient_icustay: 3.56s

 47%|████▋     | 203/429 [09:55<12:10,  3.23s/it]

get_patient_icustay: 3.53s

 48%|████▊     | 204/429 [09:59<12:33,  3.35s/it]

get_patient_icustay: 3.56s

 48%|████▊     | 205/429 [10:03<13:27,  3.61s/it]

get_patient_icustay: 4.02s

 48%|████▊     | 206/429 [10:08<14:46,  3.97s/it]

get_patient_icustay: 4.77s

 48%|████▊     | 207/429 [10:12<14:48,  4.00s/it]

get_patient_icustay: 4.02s

 48%|████▊     | 208/429 [10:13<11:01,  2.99s/it]

get_patient_icustay: 0.52s

 49%|████▊     | 209/429 [10:13<08:18,  2.27s/it]

get_patient_icustay: 0.50s

 49%|████▉     | 210/429 [10:17<09:46,  2.68s/it]

get_patient_icustay: 3.58s

 49%|████▉     | 211/429 [10:21<10:50,  2.98s/it]

get_patient_icustay: 3.59s

 49%|████▉     | 212/429 [10:24<11:26,  3.16s/it]

get_patient_icustay: 3.52s

 50%|████▉     | 213/429 [10:28<11:52,  3.30s/it]

get_patient_icustay: 3.56s

 50%|████▉     | 214/429 [10:31<12:12,  3.41s/it]

get_patient_icustay: 3.60s

 50%|█████     | 215/429 [10:32<09:08,  2.56s/it]

get_patient_icustay: 0.53s

 50%|█████     | 216/429 [10:36<10:13,  2.88s/it]

get_patient_icustay: 3.56s

 51%|█████     | 217/429 [10:39<11:05,  3.14s/it]

get_patient_icustay: 3.69s

 51%|█████     | 218/429 [10:43<11:30,  3.27s/it]

get_patient_icustay: 3.53s

 51%|█████     | 219/429 [10:44<08:33,  2.45s/it]

get_patient_icustay: 0.46s

 51%|█████▏    | 220/429 [10:44<06:41,  1.92s/it]

get_patient_icustay: 0.63s

 52%|█████▏    | 221/429 [10:48<08:23,  2.42s/it]

get_patient_icustay: 3.53s

 52%|█████▏    | 222/429 [10:48<06:30,  1.88s/it]

get_patient_icustay: 0.46s

 52%|█████▏    | 223/429 [10:49<05:05,  1.48s/it]

get_patient_icustay: 0.47s

 52%|█████▏    | 224/429 [10:53<07:12,  2.11s/it]

get_patient_icustay: 3.53s

 52%|█████▏    | 225/429 [10:56<08:45,  2.58s/it]

get_patient_icustay: 3.55s

 53%|█████▎    | 226/429 [10:57<06:35,  1.95s/it]

get_patient_icustay: 0.43s

 53%|█████▎    | 227/429 [11:00<08:19,  2.47s/it]

get_patient_icustay: 3.62s

 53%|█████▎    | 228/429 [11:04<09:20,  2.79s/it]

get_patient_icustay: 3.40s

 53%|█████▎    | 229/429 [11:08<10:09,  3.05s/it]

get_patient_icustay: 3.59s

 54%|█████▎    | 230/429 [11:08<07:35,  2.29s/it]

get_patient_icustay: 0.46s

 54%|█████▍    | 231/429 [11:12<08:59,  2.72s/it]

get_patient_icustay: 3.68s

 54%|█████▍    | 232/429 [11:12<06:49,  2.08s/it]

get_patient_icustay: 0.51s

 54%|█████▍    | 233/429 [11:13<05:10,  1.58s/it]

get_patient_icustay: 0.36s

 55%|█████▍    | 234/429 [11:13<04:09,  1.28s/it]

get_patient_icustay: 0.51s

 55%|█████▍    | 235/429 [11:17<06:24,  1.98s/it]

get_patient_icustay: 3.56s

 55%|█████▌    | 236/429 [11:21<08:03,  2.51s/it]

get_patient_icustay: 3.68s

 55%|█████▌    | 237/429 [11:21<06:07,  1.91s/it]

get_patient_icustay: 0.47s

 55%|█████▌    | 238/429 [11:25<07:50,  2.46s/it]

get_patient_icustay: 3.69s

 56%|█████▌    | 239/429 [11:29<08:53,  2.81s/it]

get_patient_icustay: 3.56s

 56%|█████▌    | 240/429 [11:32<09:36,  3.05s/it]

get_patient_icustay: 3.56s

 56%|█████▌    | 241/429 [11:36<10:05,  3.22s/it]

get_patient_icustay: 3.49s

 56%|█████▋    | 242/429 [11:36<07:32,  2.42s/it]

get_patient_icustay: 0.50s

 57%|█████▋    | 243/429 [11:37<05:53,  1.90s/it]

get_patient_icustay: 0.55s

 57%|█████▋    | 244/429 [11:38<04:34,  1.49s/it]

get_patient_icustay: 0.47s

 57%|█████▋    | 245/429 [11:41<06:29,  2.12s/it]

get_patient_icustay: 3.53s

 57%|█████▋    | 246/429 [11:42<05:05,  1.67s/it]

get_patient_icustay: 0.50s

 58%|█████▊    | 247/429 [11:42<04:03,  1.34s/it]

get_patient_icustay: 0.49s

 58%|█████▊    | 248/429 [11:43<03:21,  1.12s/it]

get_patient_icustay: 0.53s

 58%|█████▊    | 249/429 [11:47<05:37,  1.87s/it]

get_patient_icustay: 3.52s

 58%|█████▊    | 250/429 [11:50<07:07,  2.39s/it]

get_patient_icustay: 3.53s

 59%|█████▊    | 251/429 [11:54<08:15,  2.78s/it]

get_patient_icustay: 3.65s

 59%|█████▊    | 252/429 [11:57<08:51,  3.00s/it]

get_patient_icustay: 3.46s

 59%|█████▉    | 253/429 [11:58<06:39,  2.27s/it]

get_patient_icustay: 0.49s

 59%|█████▉    | 254/429 [12:02<07:51,  2.70s/it]

get_patient_icustay: 3.63s

 59%|█████▉    | 255/429 [12:05<08:40,  2.99s/it]

get_patient_icustay: 3.56s

 60%|█████▉    | 256/429 [12:09<09:06,  3.16s/it]

get_patient_icustay: 3.49s

 60%|█████▉    | 257/429 [12:12<09:23,  3.27s/it]

get_patient_icustay: 3.49s

 60%|██████    | 258/429 [12:13<07:05,  2.49s/it]

get_patient_icustay: 0.54s

 60%|██████    | 259/429 [12:17<07:56,  2.81s/it]

get_patient_icustay: 3.48s

 61%|██████    | 260/429 [12:20<08:34,  3.04s/it]

get_patient_icustay: 3.55s

 61%|██████    | 261/429 [12:24<09:02,  3.23s/it]

get_patient_icustay: 3.53s

 61%|██████    | 262/429 [12:27<09:14,  3.32s/it]

get_patient_icustay: 3.47s

 61%|██████▏   | 263/429 [12:28<06:51,  2.48s/it]

get_patient_icustay: 0.46s

 62%|██████▏   | 264/429 [12:32<07:42,  2.81s/it]

get_patient_icustay: 3.45s

 62%|██████▏   | 265/429 [12:35<08:19,  3.04s/it]

get_patient_icustay: 3.55s

 62%|██████▏   | 266/429 [12:39<08:45,  3.23s/it]

get_patient_icustay: 3.59s

 62%|██████▏   | 267/429 [12:42<09:03,  3.36s/it]

get_patient_icustay: 3.54s

 62%|██████▏   | 268/429 [12:46<09:11,  3.42s/it]

get_patient_icustay: 3.52s

 63%|██████▎   | 269/429 [12:49<09:09,  3.43s/it]

get_patient_icustay: 3.40s

 63%|██████▎   | 270/429 [12:50<06:49,  2.57s/it]

get_patient_icustay: 0.45s

 63%|██████▎   | 271/429 [12:54<07:36,  2.89s/it]

get_patient_icustay: 3.56s

 63%|██████▎   | 272/429 [12:57<08:09,  3.12s/it]

get_patient_icustay: 3.59s

 64%|██████▎   | 273/429 [13:01<08:29,  3.27s/it]

get_patient_icustay: 3.49s

 64%|██████▍   | 274/429 [13:05<08:44,  3.38s/it]

get_patient_icustay: 3.59s

 64%|██████▍   | 275/429 [13:05<06:29,  2.53s/it]

get_patient_icustay: 0.47s

 64%|██████▍   | 276/429 [13:06<04:59,  1.96s/it]

get_patient_icustay: 0.49s

 65%|██████▍   | 277/429 [13:09<06:12,  2.45s/it]

get_patient_icustay: 3.54s

 65%|██████▍   | 278/429 [13:13<07:00,  2.79s/it]

get_patient_icustay: 3.50s

 65%|██████▌   | 279/429 [13:17<07:34,  3.03s/it]

get_patient_icustay: 3.49s

 65%|██████▌   | 280/429 [13:17<05:40,  2.29s/it]

get_patient_icustay: 0.50s

 66%|██████▌   | 281/429 [13:21<06:35,  2.67s/it]

get_patient_icustay: 3.50s

 66%|██████▌   | 282/429 [13:24<07:14,  2.96s/it]

get_patient_icustay: 3.51s

 66%|██████▌   | 283/429 [13:28<07:40,  3.15s/it]

get_patient_icustay: 3.55s

 66%|██████▌   | 284/429 [13:31<07:55,  3.28s/it]

get_patient_icustay: 3.52s

 66%|██████▋   | 285/429 [13:35<08:23,  3.49s/it]

get_patient_icustay: 3.83s

 67%|██████▋   | 286/429 [13:40<08:46,  3.68s/it]

get_patient_icustay: 4.05s

 67%|██████▋   | 287/429 [13:43<08:40,  3.66s/it]

get_patient_icustay: 3.56s

 67%|██████▋   | 288/429 [13:47<08:36,  3.66s/it]

get_patient_icustay: 3.54s

 67%|██████▋   | 289/429 [13:47<06:19,  2.71s/it]

get_patient_icustay: 0.44s

 68%|██████▊   | 290/429 [13:51<06:54,  2.98s/it]

get_patient_icustay: 3.57s

 68%|██████▊   | 291/429 [13:55<07:19,  3.18s/it]

get_patient_icustay: 3.53s

 68%|██████▊   | 292/429 [13:58<07:33,  3.31s/it]

get_patient_icustay: 3.54s

 68%|██████▊   | 293/429 [14:02<07:44,  3.41s/it]

get_patient_icustay: 3.61s

 69%|██████▊   | 294/429 [14:05<07:47,  3.46s/it]

get_patient_icustay: 3.43s

 69%|██████▉   | 295/429 [14:09<07:50,  3.51s/it]

get_patient_icustay: 3.56s

 69%|██████▉   | 296/429 [14:13<07:49,  3.53s/it]

get_patient_icustay: 3.52s

 69%|██████▉   | 297/429 [14:16<07:55,  3.60s/it]

get_patient_icustay: 3.67s

 69%|██████▉   | 298/429 [14:20<07:52,  3.61s/it]

get_patient_icustay: 3.56s

 70%|██████▉   | 299/429 [14:24<07:46,  3.59s/it]

get_patient_icustay: 3.48s

 70%|██████▉   | 300/429 [14:27<07:50,  3.64s/it]

get_patient_icustay: 3.72s

 70%|███████   | 301/429 [14:28<05:48,  2.72s/it]

get_patient_icustay: 0.51s

 70%|███████   | 302/429 [14:32<06:21,  3.00s/it]

get_patient_icustay: 3.60s

 71%|███████   | 303/429 [14:35<06:42,  3.20s/it]

get_patient_icustay: 3.54s

 71%|███████   | 304/429 [14:39<06:59,  3.35s/it]

get_patient_icustay: 3.66s

 71%|███████   | 305/429 [14:39<05:10,  2.50s/it]

get_patient_icustay: 0.46s

 71%|███████▏  | 306/429 [14:43<05:53,  2.87s/it]

get_patient_icustay: 3.61s

 72%|███████▏  | 307/429 [14:47<06:17,  3.09s/it]

get_patient_icustay: 3.56s

 72%|███████▏  | 308/429 [14:51<06:36,  3.27s/it]

get_patient_icustay: 3.63s

 72%|███████▏  | 309/429 [14:54<06:52,  3.44s/it]

get_patient_icustay: 3.69s

 72%|███████▏  | 310/429 [14:58<06:54,  3.49s/it]

get_patient_icustay: 3.54s

 72%|███████▏  | 311/429 [15:01<06:52,  3.50s/it]

get_patient_icustay: 3.47s

 73%|███████▎  | 312/429 [15:05<06:51,  3.52s/it]

get_patient_icustay: 3.45s

 73%|███████▎  | 313/429 [15:09<06:51,  3.55s/it]

get_patient_icustay: 3.53s

 73%|███████▎  | 314/429 [15:12<06:57,  3.63s/it]

get_patient_icustay: 3.75s

 73%|███████▎  | 315/429 [15:16<06:53,  3.62s/it]

get_patient_icustay: 3.55s

 74%|███████▎  | 316/429 [15:20<06:50,  3.63s/it]

get_patient_icustay: 3.60s

 74%|███████▍  | 317/429 [15:23<06:45,  3.62s/it]

get_patient_icustay: 3.54s

 74%|███████▍  | 318/429 [15:24<05:03,  2.74s/it]

get_patient_icustay: 0.55s

 74%|███████▍  | 319/429 [15:24<03:47,  2.07s/it]

get_patient_icustay: 0.44s

 75%|███████▍  | 320/429 [15:28<04:35,  2.53s/it]

get_patient_icustay: 3.55s

 75%|███████▍  | 321/429 [15:29<03:30,  1.95s/it]

get_patient_icustay: 0.46s

 75%|███████▌  | 322/429 [15:32<04:24,  2.47s/it]

get_patient_icustay: 3.64s

 75%|███████▌  | 323/429 [15:36<04:56,  2.80s/it]

get_patient_icustay: 3.49s

 76%|███████▌  | 324/429 [15:40<05:22,  3.08s/it]

get_patient_icustay: 3.68s

 76%|███████▌  | 325/429 [15:40<04:01,  2.33s/it]

get_patient_icustay: 0.52s

 76%|███████▌  | 326/429 [15:44<04:39,  2.71s/it]

get_patient_icustay: 3.55s

 76%|███████▌  | 327/429 [15:47<05:03,  2.98s/it]

get_patient_icustay: 3.48s

 76%|███████▋  | 328/429 [15:51<05:22,  3.19s/it]

get_patient_icustay: 3.62s

 77%|███████▋  | 329/429 [15:55<05:29,  3.30s/it]

get_patient_icustay: 3.48s

 77%|███████▋  | 330/429 [15:58<05:37,  3.41s/it]

get_patient_icustay: 3.57s

 77%|███████▋  | 331/429 [15:59<04:08,  2.54s/it]

get_patient_icustay: 0.43s

 77%|███████▋  | 332/429 [15:59<03:07,  1.93s/it]

get_patient_icustay: 0.45s

 78%|███████▊  | 333/429 [16:00<02:26,  1.53s/it]

get_patient_icustay: 0.51s

 78%|███████▊  | 334/429 [16:01<01:58,  1.25s/it]

get_patient_icustay: 0.53s

 78%|███████▊  | 335/429 [16:04<03:08,  2.00s/it]

get_patient_icustay: 3.71s

 78%|███████▊  | 336/429 [16:08<03:53,  2.51s/it]

get_patient_icustay: 3.57s

 79%|███████▊  | 337/429 [16:12<04:21,  2.84s/it]

get_patient_icustay: 3.57s

 79%|███████▉  | 338/429 [16:15<04:39,  3.07s/it]

get_patient_icustay: 3.54s

 79%|███████▉  | 339/429 [16:16<03:27,  2.30s/it]

get_patient_icustay: 0.45s

 79%|███████▉  | 340/429 [16:19<04:00,  2.70s/it]

get_patient_icustay: 3.57s

 79%|███████▉  | 341/429 [16:23<04:22,  2.99s/it]

get_patient_icustay: 3.60s

 80%|███████▉  | 342/429 [16:27<04:35,  3.17s/it]

get_patient_icustay: 3.48s

 80%|███████▉  | 343/429 [16:27<03:24,  2.38s/it]

get_patient_icustay: 0.46s

 80%|████████  | 344/429 [16:31<03:55,  2.77s/it]

get_patient_icustay: 3.63s

 80%|████████  | 345/429 [16:35<04:24,  3.15s/it]

get_patient_icustay: 3.91s

 81%|████████  | 346/429 [16:35<03:14,  2.35s/it]

get_patient_icustay: 0.42s

 81%|████████  | 347/429 [16:36<02:27,  1.80s/it]

get_patient_icustay: 0.46s

 81%|████████  | 348/429 [16:37<01:58,  1.46s/it]

get_patient_icustay: 0.52s

 81%|████████▏ | 349/429 [16:41<02:57,  2.22s/it]

get_patient_icustay: 3.93s

 82%|████████▏ | 350/429 [16:41<02:17,  1.73s/it]

get_patient_icustay: 0.49s

 82%|████████▏ | 351/429 [16:45<03:02,  2.33s/it]

get_patient_icustay: 3.67s

 82%|████████▏ | 352/429 [16:48<03:27,  2.70s/it]

get_patient_icustay: 3.47s

 82%|████████▏ | 353/429 [16:52<03:45,  2.97s/it]

get_patient_icustay: 3.49s

 83%|████████▎ | 354/429 [16:56<03:55,  3.14s/it]

get_patient_icustay: 3.49s

 83%|████████▎ | 355/429 [16:59<04:02,  3.28s/it]

get_patient_icustay: 3.54s

 83%|████████▎ | 356/429 [17:00<02:58,  2.45s/it]

get_patient_icustay: 0.44s

 83%|████████▎ | 357/429 [17:00<02:15,  1.89s/it]

get_patient_icustay: 0.52s

 83%|████████▎ | 358/429 [17:04<02:51,  2.42s/it]

get_patient_icustay: 3.60s

 84%|████████▎ | 359/429 [17:08<03:15,  2.80s/it]

get_patient_icustay: 3.57s

 84%|████████▍ | 360/429 [17:11<03:29,  3.03s/it]

get_patient_icustay: 3.51s

 84%|████████▍ | 361/429 [17:15<03:39,  3.23s/it]

get_patient_icustay: 3.64s

 84%|████████▍ | 362/429 [17:18<03:43,  3.33s/it]

get_patient_icustay: 3.52s

 85%|████████▍ | 363/429 [17:22<03:45,  3.41s/it]

get_patient_icustay: 3.54s

 85%|████████▍ | 364/429 [17:26<03:44,  3.46s/it]

get_patient_icustay: 3.49s

 85%|████████▌ | 365/429 [17:26<02:45,  2.59s/it]

get_patient_icustay: 0.50s

 85%|████████▌ | 366/429 [17:30<03:03,  2.91s/it]

get_patient_icustay: 3.60s

 86%|████████▌ | 367/429 [17:30<02:15,  2.19s/it]

get_patient_icustay: 0.45s

 86%|████████▌ | 368/429 [17:34<02:40,  2.63s/it]

get_patient_icustay: 3.61s

 86%|████████▌ | 369/429 [17:38<02:56,  2.94s/it]

get_patient_icustay: 3.61s

 86%|████████▌ | 370/429 [17:41<03:06,  3.15s/it]

get_patient_icustay: 3.59s

 86%|████████▋ | 371/429 [17:45<03:09,  3.27s/it]

get_patient_icustay: 3.49s

 87%|████████▋ | 372/429 [17:48<03:12,  3.38s/it]

get_patient_icustay: 3.59s

 87%|████████▋ | 373/429 [17:52<03:13,  3.46s/it]

get_patient_icustay: 3.55s

 87%|████████▋ | 374/429 [17:56<03:12,  3.49s/it]

get_patient_icustay: 3.46s

 87%|████████▋ | 375/429 [17:59<03:10,  3.53s/it]

get_patient_icustay: 3.55s

 88%|████████▊ | 376/429 [18:03<03:07,  3.54s/it]

get_patient_icustay: 3.50s

 88%|████████▊ | 377/429 [18:07<03:06,  3.59s/it]

get_patient_icustay: 3.60s

 88%|████████▊ | 378/429 [18:10<03:02,  3.58s/it]

get_patient_icustay: 3.49s

 88%|████████▊ | 379/429 [18:14<02:59,  3.59s/it]

get_patient_icustay: 3.54s

 89%|████████▊ | 380/429 [18:17<02:56,  3.61s/it]

get_patient_icustay: 3.55s

 89%|████████▉ | 381/429 [18:18<02:08,  2.69s/it]

get_patient_icustay: 0.48s

 89%|████████▉ | 382/429 [18:18<01:35,  2.04s/it]

get_patient_icustay: 0.46s

 89%|████████▉ | 383/429 [18:19<01:13,  1.60s/it]

get_patient_icustay: 0.46s

 90%|████████▉ | 384/429 [18:20<00:57,  1.28s/it]

get_patient_icustay: 0.47s

 90%|████████▉ | 385/429 [18:20<00:46,  1.06s/it]

get_patient_icustay: 0.49s

 90%|████████▉ | 386/429 [18:21<00:38,  1.10it/s]

get_patient_icustay: 0.42s

 90%|█████████ | 387/429 [18:24<01:11,  1.71s/it]

get_patient_icustay: 3.52s

 90%|█████████ | 388/429 [18:28<01:32,  2.26s/it]

get_patient_icustay: 3.49s

 91%|█████████ | 389/429 [18:31<01:47,  2.69s/it]

get_patient_icustay: 3.62s

 91%|█████████ | 390/429 [18:32<01:20,  2.06s/it]

get_patient_icustay: 0.52s

 91%|█████████ | 391/429 [18:36<01:39,  2.63s/it]

get_patient_icustay: 3.89s

 91%|█████████▏| 392/429 [18:40<01:48,  2.94s/it]

get_patient_icustay: 3.56s

 92%|█████████▏| 393/429 [18:43<01:54,  3.17s/it]

get_patient_icustay: 3.63s

 92%|█████████▏| 394/429 [18:47<01:55,  3.30s/it]

get_patient_icustay: 3.54s

 92%|█████████▏| 395/429 [18:51<01:54,  3.38s/it]

get_patient_icustay: 3.50s

 92%|█████████▏| 396/429 [18:54<01:53,  3.44s/it]

get_patient_icustay: 3.53s

 93%|█████████▎| 397/429 [18:58<01:52,  3.52s/it]

get_patient_icustay: 3.65s

 93%|█████████▎| 398/429 [19:01<01:50,  3.56s/it]

get_patient_icustay: 3.52s

 93%|█████████▎| 399/429 [19:05<01:45,  3.53s/it]

get_patient_icustay: 3.39s

 93%|█████████▎| 400/429 [19:09<01:44,  3.59s/it]

get_patient_icustay: 3.67s

 93%|█████████▎| 401/429 [19:12<01:40,  3.57s/it]

get_patient_icustay: 3.48s

 94%|█████████▎| 402/429 [19:13<01:12,  2.70s/it]

get_patient_icustay: 0.53s

 94%|█████████▍| 403/429 [19:17<01:18,  3.01s/it]

get_patient_icustay: 3.70s

 94%|█████████▍| 404/429 [19:17<00:56,  2.27s/it]

get_patient_icustay: 0.48s

 94%|█████████▍| 405/429 [19:18<00:42,  1.76s/it]

get_patient_icustay: 0.45s

 95%|█████████▍| 406/429 [19:18<00:32,  1.39s/it]

get_patient_icustay: 0.46s

 95%|█████████▍| 407/429 [19:22<00:45,  2.05s/it]

get_patient_icustay: 3.52s

 95%|█████████▌| 408/429 [19:26<00:53,  2.55s/it]

get_patient_icustay: 3.57s

 95%|█████████▌| 409/429 [19:29<00:57,  2.87s/it]

get_patient_icustay: 3.57s

 96%|█████████▌| 410/429 [19:33<00:58,  3.08s/it]

get_patient_icustay: 3.52s

 96%|█████████▌| 411/429 [19:36<00:58,  3.26s/it]

get_patient_icustay: 3.54s

 96%|█████████▌| 412/429 [19:40<00:57,  3.41s/it]

get_patient_icustay: 3.69s

 96%|█████████▋| 413/429 [19:44<00:55,  3.46s/it]

get_patient_icustay: 3.52s

 97%|█████████▋| 414/429 [19:47<00:52,  3.52s/it]

get_patient_icustay: 3.53s

 97%|█████████▋| 415/429 [19:51<00:49,  3.54s/it]

get_patient_icustay: 3.54s

 97%|█████████▋| 416/429 [19:55<00:46,  3.55s/it]

get_patient_icustay: 3.52s

 97%|█████████▋| 417/429 [19:58<00:42,  3.57s/it]

get_patient_icustay: 3.49s

 97%|█████████▋| 418/429 [20:02<00:39,  3.59s/it]

get_patient_icustay: 3.55s

 98%|█████████▊| 419/429 [20:05<00:35,  3.59s/it]

get_patient_icustay: 3.55s

 98%|█████████▊| 420/429 [20:09<00:32,  3.62s/it]

get_patient_icustay: 3.56s

 98%|█████████▊| 421/429 [20:13<00:28,  3.60s/it]

get_patient_icustay: 3.50s

 98%|█████████▊| 422/429 [20:16<00:25,  3.62s/it]

get_patient_icustay: 3.59s

 99%|█████████▊| 423/429 [20:20<00:21,  3.62s/it]

get_patient_icustay: 3.55s

 99%|█████████▉| 424/429 [20:24<00:18,  3.62s/it]

get_patient_icustay: 3.56s

 99%|█████████▉| 425/429 [20:27<00:14,  3.61s/it]

get_patient_icustay: 3.53s

 99%|█████████▉| 426/429 [20:31<00:10,  3.66s/it]

get_patient_icustay: 3.65s

100%|█████████▉| 427/429 [20:35<00:07,  3.70s/it]

get_patient_icustay: 3.73s

100%|█████████▉| 428/429 [20:38<00:03,  3.68s/it]

get_patient_icustay: 3.56s

100%|██████████| 429/429 [20:42<00:00,  2.90s/it]

get_patient_icustay: 3.69s

~3s/item

## Examples

In [62]:
# ICUstay_test = pickle.load(open('D:/Master Dataset/ICUstay_30000646.pkl','rb'))
ICUstay_test = pickle.load(open(ICU_path / 'ICUstay_31205490.pkl','rb'))

In [63]:
ICUstay_test.__dict__.keys()

dict_keys(['core', 'admissions', 'patients', 'transfers', 'diagnoses_icd', 'procedures_icd', 'drgcodes', 'services', 'labevents', 'hcpcsevents', 'microbiologyevents', 'emar', 'poe', 'prescriptions', 'icustays', 'procedureevents', 'outputevents', 'inputevents', 'datetimeevents', 'chartevents', 'ingredientevents', 'cxr_split', 'cxr_metadata', 'cxr_chexpert', 'cxr_negbio', 'cxr_image_path', 'cxr_text_path', 'dsnotes', 'radnotes'])

In [64]:
with tqdm(total=len(ICUstay_test.__dict__.keys())) as pbar:
    for attribute, value in ICUstay_test.__dict__.items():
        if isinstance(value,pd.DataFrame):
            print(attribute)
            display(value.head())
            pbar.update(1)
        else:
            pbar.update(1)

  0%|          | 0/29 [00:00<?, ?it/s]

core

,subject_id,hadm_id,stay_id,study_id,dicom_id,ds_note_id,rad_note_id
19,10001725,25563031,31205490,NaN,None,10001725-DS-12,None

admissions

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
69,10001725,25563031,2110-04-11 15:08:00,2110-04-14 15:00:00,NaT,EW EMER.,P32W56,PACU,HOME,Private,English,MARRIED,WHITE,NaT,NaT,0

icustays

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
5,10001725,25563031,31205490,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2110-04-11 15:52:22,2110-04-12 23:59:56,1.338588

cxr_metadata

Empty DataFrame
Columns: [dicom_id, subject_id, study_id, PerformedProcedureStepDescription, ViewPosition, Rows, Columns, StudyDate, StudyTime, ProcedureCodeSequence_CodeMeaning, ViewCodeSequence_CodeMeaning, PatientOrientationCodeSequence_CodeMeaning, StudyDatetime]
Index: []

cxr_image_path

Empty DataFrame
Columns: [subject_id, study_id, dicom_id, path]
Index: []

dsnotes

,subject_id,hadm_id,note_id,note_type,note_seq,charttime,storetime,text
0,10001725,25563031,10001725-DS-12,DS,12,2110-04-14,2110-04-19 17:44:00,Name: ___ Unit No: ___ Admi...

radnotes

Empty DataFrame
Columns: [subject_id, hadm_id, note_id, note_type, note_seq, charttime, storetime, text]
Index: []

100%|██████████| 29/29 [00:00<00:00, 431.06it/s]